In [23]:
#Import Libary yang di gunakan
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [9]:
#Import dataset yang di gunakan
dataset = pd.read_excel('Ciri_jamur.xlsx')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['Cembung' 'Halus' 'Coklat' ... 'Hitam' 'Tersebar' 'Perkotaan']
 ['Cembung' 'Halus' 'Kuning' ... 'coklat' 'Banyak' 'Rumput Rumputan']
 ['Lonceng' 'Halus' 'Putih' ... 'coklat' 'Banyak' 'Padang Rumput']
 ...
 ['Datar' 'Halus' 'Coklat' ... 'Buff' 'Berkerumun' 'Dedaunan']
 ['kenop' 'Bersisik' 'Coklat' ... 'Putih' 'Beberapa' 'Dedaunan']
 ['Cembung' 'Halus' 'Coklat' ... 'Orange' 'Berkerumun' 'Dedaunan']]


In [5]:
print(Y)

['Beracun' 'Tidak Beracun' 'Tidak Beracun' ... 'Tidak Beracun' 'Beracun'
 'Tidak Beracun']


In [19]:
#Encoding Data Kategori
label_encoder = LabelEncoder()
for i in range(X.shape[1]):
    if isinstance(X[0,i], str):
        X[:, i] = label_encoder.fit_transform(X[:, i])
print(X)

[[1 2 3 ... 3 5 5]
 [1 2 5 ... 8 0 6]
 [4 2 8 ... 8 0 4]
 ...
 [2 2 3 ... 0 2 0]
 [5 1 3 ... 6 1 0]
 [1 2 3 ... 5 2 0]]


In [20]:
#Encoding Data Class/Label
le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[0 1 1 ... 1 0 1]


In [22]:
#embagi dataset kedalam traning set dan test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=1)
print("")
print("X_train")
print(X_train)
print("")
print("X_test")
print(X_test)
print("")
print("Y_train")
print(Y_train)
print("")
print("Y_test")
print(Y_test)


X_train
[[1 0 3 ... 3 3 6]
 [1 2 0 ... 3 5 6]
 [1 1 6 ... 6 1 1]
 ...
 [2 1 0 ... 1 1 6]
 [1 0 8 ... 8 1 1]
 [1 2 1 ... 1 1 6]]

X_test
[[2 2 8 ... 3 3 6]
 [1 0 7 ... 8 1 1]
 [1 2 8 ... 8 1 1]
 ...
 [1 2 3 ... 6 1 1]
 [1 2 3 ... 8 3 6]
 [4 2 3 ... 0 1 0]]

Y_train
[1 1 0 ... 0 1 0]

Y_test
[1 0 0 ... 0 1 1]


In [24]:
#Scalling data dengan standardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

print("")
print("X_train")
print(X_train)
print("")
print("X_test")
print(X_test)



X_train
[[1 0 3 ... -0.6555473440907293 0.4023890963295805 1.4599515156577616]
 [1 2 0 ... -0.6555473440907293 1.586240041121769 1.4599515156577616]
 [1 1 6 ... 0.4964316164984507 -0.7814618484626079 -0.7497985659156216]
 ...
 [2 1 0 ... -1.4235333178168492 -0.7814618484626079 1.4599515156577616]
 [1 0 8 ... 1.2644175902245707 -0.7814618484626079 -0.7497985659156216]
 [1 2 1 ... -1.4235333178168492 -0.7814618484626079 1.4599515156577616]]

X_test
[[2 2 8 ... -0.6555473440907293 0.4023890963295805 1.4599515156577616]
 [1 0 7 ... 1.2644175902245707 -0.7814618484626079 -0.7497985659156216]
 [1 2 8 ... 1.2644175902245707 -0.7814618484626079 -0.7497985659156216]
 ...
 [1 2 3 ... 0.4964316164984507 -0.7814618484626079 -0.7497985659156216]
 [1 2 3 ... 1.2644175902245707 0.4023890963295805 1.4599515156577616]
 [4 2 3 ... -1.8075263046799093 -0.7814618484626079 -1.1917485822302982]]
